# NOTE: This docker-compose file was constructed to create a base for
# use by the End-to-end tests. It has not been fully tested for use in
# constructing a true, stand-alone sync server.
# If you're interested in doing that, please join our community in the
# github issues and comments.
#
# Application runs off of port 8000.
# you can test if it's available with
# curl "http://localhost:8000/__heartbeat__"

version: "3"
services:
  mock-fxa-server:
    image: app:build-sqlite
    restart: "no"
    entrypoint: "sh scripts/start_mock_fxa_server.sh"
    environment:
      MOCK_FXA_SERVER_HOST: 0.0.0.0
      MOCK_FXA_SERVER_PORT: 6000

  syncserver:
    # NOTE: The naming in the rest of this repository has been updated to reflect the fact
    # that Syncstorage and Tokenserver are now part of one repository/server called
    # "Syncserver" (updated from "syncstorage-rs"). We keep the legacy naming below for
    # backwards compatibility with previous Docker images.
    image: ${SYNCSTORAGE_RS_IMAGE:-syncstorage-rs:latest}
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/data/
    environment:
      SYNC_HOST: 0.0.0.0
      SYNC_MASTER_SECRET: secret0
      SYNC_SYNCSTORAGE__DATABASE_URL: sqlite:///data/syncdb.sqlite
      SYNC_TOKENSERVER__DATABASE_URL: sqlite:///data/tokenserverdb.sqlite
      SYNC_TOKENSERVER__RUN_MIGRATIONS: "true"

volumes:
  sqlite_data:
