[package]
name = "syncstorage-db-common"
version = "0.12.0"
edition = "2021"

[dependencies]
async-trait = "0.1.40"
backtrace = "0.3.61"
chrono = "0.4"
# Pin to 0.5 for now, to keep it under tokio 0.2 (issue977).
# Fix for #803 (deadpool#92) points to our fork for now
#deadpool = "0.5"  # pin to 0.5
deadpool = { git = "https://github.com/mozilla-services/deadpool", branch = "deadpool-v0.5.2-issue92" }
diesel = { version = "1.4", features = ["mysql", "r2d2"] }
diesel_migrations = { version = "1.4.0", features = ["mysql"] }
# Some versions of OpenSSL 1.1.1 conflict with grpcio's built-in boringssl which can cause
# syncserver to either fail to either compile, or start. In those cases, try
# `cargo build --features grpcio/openssl ...`
grpcio = { version = "0.10" }
hostname = "0.3.1"
http = "0.2.6"
futures = { version = "0.3", features = ["compat"] }
lazy_static = "1.4.0"
serde = "1.0"
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
syncstorage-common = { path = "../syncstorage-common" }
thiserror = "1.0.26"
