[package]
name = "purge_ttl"
version = "0.1.0"
authors = ["mirefly <mirefly@gmail.com>"]
edition = "2018"

[dependencies]
googleapis-raw = { version = "0", path = "../../../vendor/mozilla-rust-sdk/googleapis-raw" }
grpcio = { version = "0.5.0" }
cadence = "0.19.1"
log = "0.4.8"
env_logger = "0.7.1"
