[package]
name = "tokenserver-settings"
version.workspace=true
license.workspace=true
authors.workspace=true
edition.workspace=true

[dependencies]
serde.workspace=true
jsonwebtoken.workspace=true

tokenserver-common = { path = "../tokenserver-common" }
