# Example MySQL DSN:
database_url = "mysql://sample_user:sample_password@localhost/syncstorage_rs"

# Example Spanner DSN:
# database_url="spanner://projects/SAMPLE_GCP_PROJECT/instances/SAMPLE_SPANNER_INSTANCE/databases/SAMPLE_SPANNER_DB"

"limits.max_total_records"=1666 # See issues #298/#333
master_secret = "INSERT_SECRET_KEY_HERE"

# removing this line will default to moz_json formatted logs (which is preferred for production envs)
human_logs = 1 
