[book]
title = "Mozilla Syncstorage-rs"
authors = ["Storage Team", "Barry Chen", "Philip Jenvey", "Taddes Korris"]
description = "Detailed description and operation of Mozilla's Syncstorage & Tokenserver."
language = "en"

[rust]
edition = "2021"

[build]
build-dir = "output"

[preprocessor.mermaid]
command = "mdbook-mermaid"


[output.html]
additional-css = ["style.css"]
# additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true